name: CLI Documentation Generation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cliDocsGeneration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Generate CLI docs
        run: go run internal/cli-docgen.go

      - name: Verify whether CLI documentation is up-to-date
        run: git diff --exit-code
