name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  fetchGitHubIssue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Fetch github issue
        run: go run cmd/summaraizer/summaraizer.go github --issue ioki-mobility/summaraizer/11

  summarizeOllama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Setup ollama
        run: |
          ollama serve &
          ollama pull phi3:mini

      - name: Can summarize text
        run: |
          echo '[{ "Author" : "StefMa", "Body" : "The World is a nice place" }, { "Author" : "fabrik42", "Body" : "Yes, indeed!" }]' | go run cmd/summaraizer/summaraizer.go ollama --model phi3:mini
